package app;



import classModel.ModelTabel;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.NoSuchElementException;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mysql.DBConnect;

import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ant
 */
public class frmText extends javax.swing.JFrame {

    /**
     * Creates new form frmText
     */
    public frmText() {
        super("Hitung Kata");
        initComponents();
        //    tblKata.setModel(new ModelTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKata = new javax.swing.JTable();
        btnBaca = new javax.swing.JButton();
        btnWord = new javax.swing.JButton();
        progessBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taText.setColumns(20);
        taText.setRows(5);
        jScrollPane2.setViewportView(taText);

        tblKata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kata", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(tblKata);

        btnBaca.setText("Notepad");
        btnBaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacaActionPerformed(evt);
            }
        });

        btnWord.setText("Word");
        btnWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordActionPerformed(evt);
            }
        });

        progessBar.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnBaca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnWord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(progessBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBaca)
                            .addComponent(btnWord)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progessBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacaActionPerformed
        // TODO add your handling code here:
        this.bacaText("data.txt");
        this.bacaIsiFile("data.txt");
    }//GEN-LAST:event_btnBacaActionPerformed

    private void btnWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordActionPerformed
        // TODO add your handling code here:
        this.bacaDoc("data.doc");
    }//GEN-LAST:event_btnWordActionPerformed
   void bacaDoc (String f){        
       // fungsi pembacaan doc dengan library poi
        POIFSFileSystem fs = null;
        FileInputStream fis;
        HWPFDocument doc;
        WordExtractor we;
        String[] paragraphs;

        File file = new File(f);
        try {
            fis = new FileInputStream(file);
            doc = new HWPFDocument(fis);             //get Paragraph text  as array
            we = new WordExtractor(doc);
            //get Paragraph text  as array
            paragraphs = we.getParagraphText();
            taText.setText("");
            for (int i = 0; i < paragraphs.length; i++) {
                taText.append(paragraphs[i]);
            }
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        } finally {
            progessBar.setVisible(false);
        }        
        
    }

void bacaText( String f) {
       // fungsi pembaca teks dari notepad
        taText.setText("");
        BufferedReader fileReader ;
        //proses pembacaan
        File file = new File(f);
        try{
            byte[] buffer = new byte[1024];
            BufferedInputStream bufferedInput = new BufferedInputStream(new
FileInputStream(f));
            int bytesRead = 0;
            while ((bytesRead = bufferedInput.read(buffer)) != -1) {
                String kt = new String(buffer, 0, bytesRead);
                taText.append(kt);
            }
            bufferedInput.close();
        } catch(IOException io){
            JOptionPane.showMessageDialog(null,"File not support !!","Message",JOptionPane.INFORMATION_MESSAGE);
        } catch(NoSuchElementException e){
            JOptionPane.showMessageDialog(null,"Format tidak sama !!","Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }


    private void bacaIsiFile(String path){
       // fungsi untuk membca isi file notepad untuk diolah perkata
        Vector dataKata = new Vector();
        Vector jumkata = new Vector();
        
        int count=0, loop=0;
        BufferedReader fileReader ;
        StringTokenizer st;
        File file = new File(path);
        try{
            fileReader = new BufferedReader(new FileReader(file));
            while(true){
                String line = fileReader.readLine();
                
                if (line == null)
                    break ; 
                line = line.replace(".", " ");
                line = line.replace("/", " ");
                line = line.replace("(", " ");
                line = line.replace(")", " ");
                line = line.replace(",", " ");
                line = line.replace("<", " ");
                line = line.replace(">", " ");
                line = line.replace("?", " ");
                line = line.replace("\'", " ");
                line = line.replace("\"", " ");
                line = line.replace("!", " ");
                line = line.replace("@", " ");
                line = line.replace("#", " ");
                line = line.replace("$", " ");
                line = line.replace("&", " ");
                line = line.replace(":", " ");
                line = line.replace(";", " ");
                line = line.replace("[", " ");
                line = line.replace("]", " ");
                line = line.replace("{", " ");
                line = line.replace("}", " ");
                line = line.replace("\\", " ");
                line = line.replace("|", " ");
                line = line.replace("+", " ");
                line = line.replace("=", " ");
                line = line.replace("-", " ");
                line = line.replace("*", " ");
                line = line.replace("^", " ");
                line = line.replace("%", " ");
                line = line.replace("`", " ");
                line = line.replace("~", " ");
                
                st = new StringTokenizer(line);
                while(st.hasMoreTokens()){
                    count = 1;
                    String kt = st.nextToken();
                    kt=kt.toLowerCase();
                    if (kt.equals(":")||kt.equals("|")||kt.equals("?"))
                        continue;
                    else {
                        if(dataKata.isEmpty()){
                            dataKata.add(kt);
                            jumkata.add(loop, 1);
                        } else{
                            for(int i=0; i<dataKata.size(); i++){
                               if(kt.equalsIgnoreCase(dataKata.get(i).toString())){
                                    count = Integer.parseInt(jumkata.get(i).toString());
                                    count++;
                                    jumkata.set(i, count);
                                }
                            }
                            if(count==1){
                                dataKata.add(kt);
                                loop++;
                                jumkata.add(1); 
                            }
                        }
                    }
                }
            }
            tblKata.setModel(new ModelTabel(dataKata,jumkata));
          
            this.tulisText(dataKata, jumkata, path.substring(0,
path.length()-4)+"_hasil"+path.substring(path.length()-4,path.length()));
        } catch(IOException io){
            JOptionPane.showMessageDialog(null,"No file  !!","Message",JOptionPane.INFORMATION_MESSAGE);
        } catch(NoSuchElementException e){
            JOptionPane.showMessageDialog(null,"Format tidak sama !!","Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }

private void tulisText(Vector kt, Vector jum, String target) {
        DBConnect connect = new DBConnect(); 
        String line;
        PrintWriter fout = null;
        File file1 = new File(target);
        try {
            fout = new PrintWriter(new FileWriter(file1));
            fout.flush();
            for (int i = 0; i < kt.size(); i++) {
                fout.println(kt.elementAt(i).toString() + " = " + jum.elementAt(i).toString() + "\n"); 
                connect.setDataTeks(target, kt.elementAt(i).toString(), Integer.parseInt(jum.elementAt(i).toString())); 
            }
            fout.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File tidak dapat dituliskan !!", "Message", JOptionPane.INFORMATION_MESSAGE);
            fout.close();
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmText().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaca;
    private javax.swing.JButton btnWord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar progessBar;
    private javax.swing.JTextArea taText;
    private javax.swing.JTable tblKata;
    // End of variables declaration//GEN-END:variables
}
